#pragma once

#define SPLIT_USB_DETECT
#define USE_SERIAL

#define SERIAL_USART_FULL_DUPLEX

#define EE_HANDS
#define MASTER_LEFT
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_PIN_SWAP

#define MATRIX_ROW_PINS { GP11, GP10, GP9, GP8}
#define MATRIX_COL_PINS {GP2, GP3, GP4, GP5, GP6, GP7}

#define MATRIX_ROW_PINS_RIGHT { GP11, GP10, GP9, GP8}
#define MATRIX_COL_PINS_RIGHT {GP2, GP3, GP4, GP5, GP6, GP7}

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U